version: '3.8'

services:
  weather_api:
    image: "weather_api:1.0.0"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: "mysql:8"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=clients_admin
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=clientsdb
    ports:
      - 3307:3306

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5