version: '3'

services:
  covid_api:
    image: 'covid_api:1.0.0'
    build: .
    depends_on:
      - covid_db
    ports:
      - 8080:8080

  covid_db:
    container_name: covid_db
    image: postgres:15.4
    ports:
      - 5432
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  db: